### ISSUE TITLE
I-frames on psi-j website cutting off new index.rst content

### ISSUE THREAD

**Issue by danlaney** [ExaWorks/psij-python#271] opened 2022-09-07 17:55 UTC
When using web/build.sh, and clicking on 'documentation' in the top bar, the content is clipped.  Scaling the window shows that the full content is there, but there is no scrollbar to see it.

Also: the TOC is listed below the text which we may want to remove so that it only appears on the left side.

**Comment by hategan** [comment] 2022-09-13 23:02
I can't reproduce this. I tried chrome, chromium, and firefox on linux. Both the main site and a local build.

Does the main site work ok for you? If not, what browser and os are you using?

**Comment by mturilli** [comment] 2022-09-23 16:15
@andre-merzky to test this locally via `file://`

**Comment by wilke** [comment] 2022-10-21 00:31
@hategan Is your PR addressing this issue and can we close it?

**Comment by hategan** [comment] 2022-10-21 03:00
> @hategan Is your PR addressing this issue and can we close it?

Not exactly. It can't be fixed. But it does document what the situation is. So if @danlaney is OK with that, we can close it.

**Comment by andre-merzky** [comment] 2022-11-04 16:13
This can be closed IMHO - it is fixed as well as possible and the instructions are clear enough to avoid the issue...

**Closed by andre-merzky** 2022-11-04 16:13 UTC
Labels: bug, documentation, Release
